version: 0.1.0-{build}
image: Visual Studio 2017
environment:
  matrix:
  - GENERATOR: '"Visual Studio 15 2017"'
    BUILD_TYPE: Release
    
init:
- git config --global core.autocrlf true
install:
- git submodule update --init --recursive
build_script:
# appveyor提供python版本: https://www.appveyor.com/docs/windows-images-software/#python
- cmd: >-
    mkdir build

    cd build

    cmake .. -G %GENERATOR% -DCMAKE_BUILD_TYPE=%BUILD_TYPE% -DPYTHON_EXECUTABLE:FILEPATH="C:\Python39\python.exe"

    cmake --build . --config %BUILD_TYPE% 

artifacts:
  - path: build/src/Release/ddraw.dll

test: off
